### ISSUE TITLE
Support pseduo parameter replacement in more cfn template sections

### ISSUE THREAD

**Issue by lorengordon** [svdgraaf/serverless-pseudo-parameters#12]
Right now, serverless-pseudo-parameters [iterates only over items in the Resources section](https://github.com/svdgraaf/serverless-pseudo-parameters/blob/e05cad4429b24b4ba22216528e4b8774ec3cb041/lib/index.js#L27) of the CloudFormation template.

Serverless is not restricted to just the Resources section of CloudFormation, though. Many sections can be specified in the serverless custom `resources` block, such as custom "Outputs". I'd like to propose checking for any [valid section type in the CloudFormation template anatomy](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-anatomy.html) and replacing pseudo parameters in all of them.

**Comment by svdgraaf** [comment]
I like this idea!

**Comment by svdgraaf** [comment]
This is now possible, I'm closing this issue
