### ISSUE TITLE
Git url is not shown in npmjs.com

### ISSUE THREAD

**Issue by glicht** [svdgraaf/serverless-pseudo-parameters#13]
Hi,

I noticed that npmjs is not providing a link to the github page: https://www.npmjs.com/package/serverless-pseudo-parameters 

I think the definition you have in package.json is wrong and npmjs isn't picking it up. Maybe try the following definition:

```json
"repository": {
    "type": "git",
    "url": "https://github.com/svdgraaf/serverless-pseudo-parameters"
  },
```

**Comment by svdgraaf** [comment]
Thank you, this is now fixed :)
