### ISSUE TITLE
pseudo-variables not resolved when using serverless invoke-local

### ISSUE THREAD

**Issue by afreakk** [svdgraaf/serverless-pseudo-parameters#18]
would that be possible to do ?

**Comment by svdgraaf** [comment]
Pfoeh, I'm not sure if that is a hook that we can hook into. I think it would be theoretically possible. I think.

**Comment by JGreen31** [comment]
Any progress on this item?  Would certainly make things more convenient.

**Comment by onoranzefunebricloud** [comment]
Any update on this? Still relevant
