### ISSUE TITLE
Where is #{AWS::AccountId} getting the value from?

### ISSUE THREAD

**Issue by vayias** [svdgraaf/serverless-pseudo-parameters#22]
I was wondering where is `#{AWS::AccountId}` getting the value from?
Is it looking at the account associated with `~/.aws/credentials`?

Is there any way to still use `#{AWS::AccountId}` but force it to get the value from environment variables or something like that?

**Comment by svdgraaf** [comment]
These are so called "pseudo parameters" (hence the name of this plugin), and are baked in CloudFormation. You can find the documentation on those parameters here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html

If you want to reference environment variables from your local environment, you can use the regular Serverless parsing, eg: `${env:MY_ENV_VAR}`
