### ISSUE TITLE
Pseudo Parameters not replaced for individual functions

### ISSUE THREAD

**Issue by skharel** [svdgraaf/serverless-pseudo-parameters#34]
When using the serverless deployment command `sls deploy -s dev` to deploy the complete stack the pseudo variables such as ${AWS::Region},  ${AWS::AccountId} are properly populated with the actual values. During the build I can see in the logs that AWS Pseudo Parameters are getting replaced.

However, when deploying individual lambda function from this stack using the command `sls deploy -f myFunction -s dev`, the pseudo parameters are not getting replaced. I do not see any logs related to AWS Pseudo Parameters.

**Comment by odanylch** [comment]
Having the same issue with deploying individual lambda as described above. Please let me know what would be the solution to that. 
Thank you.

**Comment by odanylch** [comment]
Having the same issue with deploying individual lambda as described above. Please let me know what would be the solution to that.
Thank you.

**Comment by OurNewestMember** [comment]
Noticing the same.
...Also noticing an additional lingering effect: updating the full stack afterward still did not "undo" some issues observed with pseudo parameter expansion.


`# business as usual:`
`sls deploy --stage test`
`# the issue described here:`
`sls deploy --stage test --function testLambda`
`# this still did not undo some impacts from the previous command:`
`sls deploy --stage dev`


The last command still didn't fix the pseudo parameter expansion issue experienced in the second command.

?  ...Assuming this is because the contents of the lambda handler did not change (so the lambda was not updated by the full stack update), but this left incorrect Lambda environment variables from command 2 (ie, experiencing the issue reported here)

**Comment by revmischa** [comment]
Also having the same issue. `sls deploy` works but `sls deploy -f app` is not interpolating:
```
  layers:
    psycopg: "arn:aws:lambda:#{AWS::Region}:898466741470:layer:psycopg2-py37:3"
```

```
  1 validation error detected: Value '[arn:aws:lambda:#{AWS::Region}:898466741470:layer:psycopg2-py37:3]' at 'layers' failed to satisfy constraint: Member must satisfy constraint: [Member must have length less than or equal to 140, Member must have length greater than or equal to 1, Member must satisfy regular expression pattern: (arn:[a-zA-Z0-9-]+:lambda:[a-zA-Z0-9-]+:\d{12}:layer:[a-zA-Z0-9-_]+:[0-9]+)|(arn:[a-zA-Z0-9-]+:lambda:::awslayer:[a-zA-Z0-9-_]+)]
```

**Comment by andrhamm** [comment]
I had to change my function-specific environment variable to point to a global "custom" variable (`${self:custom.my_var_with_pseudo_params}`)

**Comment by jcgsville** [comment]
Any update on why this might be happening? It seems like the problem is still present. I just encountered it on 2.5.0

**Comment by pl0xy** [comment]
Isn't this issue due to individual function deployments not triggering CloudFormation which is where the variables are filled in?

**Comment by miqueloi** [comment]
+1

**Comment by somq** [comment]
Same here, still an existing issue

**Comment by skharel** [comment]
I have gone to a point where I am not using this library anymore. AWS Pseudo parameters are natively supported in cloudformation and that is what I have been using for over a year now. No more problems!

Checkout the pseudo parameters reference here
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html

**Comment by skharel** [comment]
Just saw this note where this library is now marked as deprecated. 

Read the note below:
https://github.com/svdgraaf/serverless-pseudo-parameters/commit/91a4dac0b5bee9d241bf35633c3cfefab677f446

**Comment by somq** [comment]
> Just saw this note where this library is now marked as deprecated.
> 
> Read the note below:
> [91a4dac](https://github.com/svdgraaf/serverless-pseudo-parameters/commit/91a4dac0b5bee9d241bf35633c3cfefab677f446)

Oh yeahh, I don't know if it's just me but I feel like it's really difficult to follow serverless changes... Missed this one.
+1 for CF, but I'm still missing some useful features of serverless tho.
Thanks for your help anyway @skharel
