### ISSUE TITLE
With serverless 1.48.0 the pseudo params aren't being replaced in the function events definition

### ISSUE THREAD

**Issue by maxieduncan** [svdgraaf/serverless-pseudo-parameters#38]
Up until now the following pseudo parameters have been being replaced:
```functions:
  alert:
    handler: src/handler.alert
    events:
      - sns:
          topicName: ecogy-${opt:stage, self:provider.stage}-alerts-insufficientData
          arn: arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:ecogy-${opt:stage, self:provider.stage}-alerts-insufficientData
```

After upgrading to serverless 1.48.0 I now get the following error:
`An error occurred: AlertSnsSubscriptionEcogyintalertsinsufficientData - Invalid subscription update, region value provided [#{AWS] should be the same as the current subscription region [us-east-1]`

**Comment by maxieduncan** [comment]
I've been able to work around this by replacing `#{AWS::Region}` with `${opt:region, self:provider.region}`

**Comment by jefftham** [comment]
FYI, serverless version 1.46.0 work correctly. i believe the serverless framework changes cause some side effect to this plugin.

**Comment by jasonkuhrt** [comment]
Doesn't seem to work on `1.50.0` either.

**Comment by svdgraaf** [comment]
I finally have some time this week to take a look at this

**Comment by svdgraaf** [comment]
My hunch is that it has to do with this PR: https://github.com/serverless/serverless/pull/6366/files

Which got merged in `1.48.0` in Serverless Framework, digging a bit further.

**Comment by svdgraaf** [comment]
Oh, @bzemms actually noted that it breaks here: https://github.com/serverless/serverless/pull/6366/files#r314091245

**Comment by svdgraaf** [comment]
I create an issue on the serverless framework repo to discuss a possible solution. Could be in the plugin, could be in core.

**Comment by janikarh** [comment]
@svdgraaf Could you please link the issue here, when it is open.

**Comment by svdgraaf** [comment]
@janikarh it's mentioned above my comment, see here: https://github.com/serverless/serverless/issues/6760

**Comment by majorgilles** [comment]
also encountered this issue on sls 1.53.0. Good to see it's being worked on.

**Comment by svdgraaf** [comment]
I see a bug fix was merged, can anybody check if this fixes the issues?

https://github.com/serverless/serverless/issues/6760#event-2771097082

**Comment by maxieduncan** [comment]
This appears to be working as expected again with serverless 1.57.0

**Comment by svdgraaf** [comment]
Great, then I'll close this issue 👍

**Comment by majorgilles** [comment]
@svdgraaf I encountered the issue again in 1.62.0, or at least a similar issue with subscriptions

in the following arn def:
```
      arn: arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:${self:custom.topics.aCertainTopic.name}
```

If I try to deploy this, the subscription creation will fail and the cloud formation stack will stack stuck in UPDATE_ROLLBACK_CLEANUP_IN_PROGRESS for ~1 hour to 2 hours

If i do instead:
```
      arn: arn:aws:sns:${self:custom.currentRegion}:#{AWS::AccountId}:${self:custom.topics.aCertainTopic.name}
```

or if I use the string arn directly without substitution, everything works fine

**Comment by svdgraaf** [comment]
@majorgilles which Region are you deploying to?

**Comment by svdgraaf** [comment]
Also @majorgilles can you post the portion of the cloudformation UPDATE file where the replacement is in? I'm not sure if this is a framework, plugin or cloudformation issue
