### ISSUE TITLE
Pseudo-parameters not substituted if validate is set to true in stepFunctions

### ISSUE THREAD

**Issue by TheMadGeometer** [svdgraaf/serverless-pseudo-parameters#41]
The following snippet of code:

stepFunctions:
  validate: true
  stateMachines:
    serverlessTestStepFunc:
      name: ${self:service}-${self:provider.stage}-rmh-test-fsm
      definition:
        StartAt: MdcInsertControlRecordState
        States:
          MdcInsertControlRecordState:
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${self:provider.stage}-mdcInsertControlRecord
            InputPath: "$"
            ResultPath: "$"
            OutputPath: "$"
            End: true

fails asl validation with the error:

`Serverless Error ---------------------------------------
 
  ✕ State machine "serverlessTestStepFunc" definition is invalid:
  [{"keyword":"additionalProperties","dataPath":".States['MdcInsertControlRecordState']","schemaPath":"#/additionalProperties","params":{"additionalProperty":"Resource"},"message":"should NOT have additional properties"},{"keyword":"additionalProperties","dataPath":".States['MdcInsertControlRecordState']","schemaPath":"http://asl-validator.cloud/fail#/additionalProperties","params":{"additionalProperty":"Resource"},"message":"should NOT have additional properties"},{"keyword":"additionalProperties","dataPath":".States['MdcInsertControlRecordState']","schemaPath":"#/additionalProperties","params":{"additionalProperty":"Resource"},"message":"should NOT have additional properties"},{"keyword":"additionalProperties","dataPath":".States['MdcInsertControlRecordState']","schemaPath":"http://asl-validator.cloud/pass#/additionalProperties","params":{"additionalProperty":"Resource"},"message":"should NOT have additional properties"},{"keyword":"additionalProperties","dataPath":".States['MdcInsertControlRecordState']","schemaPath":"http://asl-validator.cloud/succeed#/additionalProperties","params":{"additionalProperty":"Resource"},"message":"should NOT have additional properties"},{"keyword":"pattern","dataPath":".States['MdcInsertControlRecordState'].Resource","schemaPath":"http://asl-validator.cloud/task#/properties/Resource/oneOf/0/pattern","params":{"pattern":"^arn:aws:([a-z]|-)+:([a-z]|[0-9]|-)*:[0-9]*:([a-z]|-)+:[a-zA-Z0-9-_.]+$"},"message":"should match pattern \"^arn:aws:([a-z]|-)+:([a-z]|[0-9]|-)*:[0-9]*:([a-z]|-)+:[a-zA-Z0-9-_.]+$\""},{"keyword":"type","dataPath":".States['MdcInsertControlRecordState'].Resource","schemaPath":"http://asl-validator.cloud/task#/properties/Resource/oneOf/1/type","params":{"type":"object"},"message":"should be object"},{"keyword":"oneOf","dataPath":".States['MdcInsertControlRecordState'].Resource","schemaPath":"http://asl-validator.cloud/task#/properties/Resource/oneOf","params":{"passingSchemas":null},"message":"should match exactly one schema in oneOf"},{"keyword":"additionalProperties","dataPath":".States['MdcInsertControlRecordState']","schemaPath":"http://asl-validator.cloud/wait#/additionalProperties","params":{"additionalProperty":"Resource"},"message":"should NOT have additional properties"},{"keyword":"oneOf","dataPath":".States['MdcInsertControlRecordState']","schemaPath":"#/oneOf","params":{"passingSchemas":null},"message":"should match exactly one schema in oneOf"}]`

If I shut off validation, then it passes and when I check the AWS console, the machine is created correctly. This leads me to believe that when the asl validator runs, the pseudo-parameters are not yet plugged in. Now, I can work around this by either setting account id and region under the provider heading, or I can shut off validation (I've tried and both work), but I think this is a small issue that should be fixed. I could also be wrong about what's causing it, but I think I've eliminated all of the other causal factors.

**Comment by medikoo** [comment]
Closing, as all functionalities as provided by this plugin are now covered by the Framework (since v2.50.0)
