### ISSUE TITLE
Escaping variables so theyre not replaced by pseudo parameters

### ISSUE THREAD

**Issue by vodlogic** [svdgraaf/serverless-pseudo-parameters#43]
Hi,

I'm trying to setup a DataPipeline for exporting DynamoDB data to S3 using Cloudformation
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-datapipeline-pipeline.html#aws-resource-datapipeline-pipeline--examples

DataPipeline references other blocks of the DataPipeline configuration using the same token format as used by serverless-pseudo-parameters e.g. `#{myOutputS3Loc}` and therefore they are getting replaced with the `Fn:Sub` intrinsic function which is not desired behaviour.

Is there currently a way to escape the token so that the resulting cloudformation template still contains the token as `#{myOutputS3Loc}`?

Cheers,

Matt

**Comment by svdgraaf** [comment]
Oh well that sucks 😅 I have to think about this one... 🤔

**Comment by vodlogic** [comment]
Thanks Sander. One thought I had was to allow escaping using soomething like `#\{myOutputS3Loc}`. Any existing parameters such as `#{AWS::AccountId}` would be replaced with `Fn::Sub` as usual and then at the end of the process, any tokens matching `#\{(.*)}` could be replaced with `#{$1}`.

I've not checked the code to see if that is appropriate but just thought I'd share some general ideas

**Comment by svdgraaf** [comment]
Yep, that could work I think

**Comment by vodlogic** [comment]
I’ve added a proposal in PR, would be grateful if you could review.

Thanks!

**Comment by svdgraaf** [comment]
I just release 2.5.0, let me know if that works as expected :)

**Comment by medikoo** [comment]
Closing, as all functionalities as provided by this plugin are now covered by the Framework (since v2.50.0)
