### ISSUE TITLE
Publish 1.2.0 changes to github?

### ISSUE THREAD

**Issue by vladgolubev** [svdgraaf/serverless-pseudo-parameters#5]
Hey,

there is version 1.2.0 on NPM released on January 25, 2018 but no commits on github since 2017

I checked the diff on upkg https://unpkg.com/serverless-pseudo-parameters@1.2.0/

But looks like just a version bump?

**Comment by j0k3r** [comment]
Maybe a late release from an old commit?

Anyway, it should be a best practice to create a release / tag on GitHub each time maintainer push a new release to NPM.

**Comment by svdgraaf** [comment]
Yeah, sorry for that, was kind of swamped. Pushed, and also now onto release 1.3.0

**Comment by j0k3r** [comment]
It could be awesome if you also create a git release / tag each time you release a new version on npm :slightly_smiling_face:

**Comment by svdgraaf** [comment]
Yeah, I should, let me create one for 1.3.0

**Comment by svdgraaf** [comment]
@j0k3r done!

**Comment by j0k3r** [comment]
Yeah thanks!
