### ISSUE TITLE
Running locally without a config file

### ISSUE THREAD

**Issue by tomardern** [svdgraaf/serverless-pseudo-parameters#71]
Hi all.

We've started to use the `serverless-pseudo-parameters` plugin, to improve our serverless.yml file, however, some of our developers are getting the following error:

`Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1`

Is there a way to run serverless with this plugin enabled locally and not have the AWS CLI installed on the user's machine.

Thanks,

**Comment by medikoo** [comment]
Closing, as all functionalities as provided by this plugin are now covered by the Framework (since v2.50.0)
