### ISSUE TITLE
In conjunction with split stacks, has issues

### ISSUE THREAD

**Issue by ssetti** [svdgraaf/serverless-pseudo-parameters#8]
It does not replace pseudo parameters in the split stack files.

Why wait until before:deploy:deploy to replace? can we get it to be much early.  Looking at split stacks, it starts at 'after:aws:package:finalize:mergeCustomProviderResources'.  So was thinking if there is a stage before that where pseudo parameter replacement can take place? like 'before:aws:package:finalize:mergeCustomProviderResources'.

**Comment by santiagocardenas** [comment]
This plugin is pretty awesome and very simple to use. However, it's limited to pseudo parameters only :(

Taking some inspiration and simplification, [serverless-cloudformation-sub-variables](https://github.com/santiagocardenas/serverless-cloudformation-sub-variables) which can probably help with what you're facing.

**Comment by svdgraaf** [comment]
@ssetti I merged and published your change as 1.4.0
@santiagocardenas very cool!

**Comment by craig-dae** [comment]
This issue is closed, but we just had this issue where params were not replaced in the stacks created by serverless-plugin-split-stacks. Can we re-open this?

**Comment by svdgraaf** [comment]
@craig-dae I recommend you open a new issue, and mention this issue if needed.
